 -- TPositivo
ALTER TABLE PERSONA ADD CONSTRAINT CK_NUMERO
CHECK (numero > 0 AND LENGTH(numero) <= 20 );
 
-- TID
ALTER TABLE PERSONA ADD CONSTRAINT CK_TIPO_ID
CHECK(tipo IN ('TI', 'CC', 'CE', 'PS'));
 
-- TCorreo
ALTER TABLE PERSONA ADD CONSTRAINT CK_CORREO
CHECK(REGEXP_LIKE (correo, '[A-Z0-9._%-]+@[A-Z0-9._%-]+\.[A-Z]{2,4}'));


-- TEstadoConductor
ALTER TABLE CONDUCTOR ADD CONSTRAINT CK_ESTADO_COND
CHECK(estado IN ('A', 'I', 'R', 'O'));

-- TEstadoVehiculo
ALTER TABLE VEHICULO ADD CONSTRAINT CK_ESTADO_VEHI
CHECK(estado IN ('A', 'I', 'R', 'O'));

-- TMoneda
ALTER TABLE SOLICITUD ADD CONSTRAINT CK_MONEDA
CHECK(MOD(precio, 100) = 0 AND precio >= 0);


-- TEstadoSolicitud
ALTER TABLE SOLICITUD ADD CONSTRAINT CK_ESTADO_SOL
CHECK(estado IN ('P', 'A', 'C', 'F'));

-- CONDUCTOR
ALTER TABLE CONDUCTOR ADD CONSTRAINT CK_LICENCIA
CHECK(LENGTH(licencia) <= 10);

-- TARJETA
ALTER TABLE TARJETA ADD CONSTRAINT CK_TARJETA_LEN
CHECK (LENGTH(numero) = 15 );