--- TABLAS
DROP TABLE persona CASCADE CONSTRAINTS;
DROP TABLE ubicacion CASCADE CONSTRAINTS;
DROP TABLE posicion CASCADE CONSTRAINTS;
DROP TABLE conductor CASCADE CONSTRAINTS;
DROP TABLE cliente CASCADE CONSTRAINTS;
DROP TABLE idioma CASCADE CONSTRAINTS;
DROP TABLE tarjeta CASCADE CONSTRAINTS;
DROP TABLE vehiculo CASCADE CONSTRAINTS;
DROP TABLE solicitud CASCADE CONSTRAINTS;

--- XPOBLAR
DELETE FROM persona;
DELETE FROM ubicacion;
DELETE FROM posicion;
DELETE FROM conductor;
DELETE FROM cliente;
DELETE FROM idioma;
DELETE FROM tarjeta;
DELETE FROM vehiculo;
DELETE FROM solicitud;

--- XTUPLAS
ALTER TABLE persona DROP CONSTRAINT CK_NUMERO;
ALTER TABLE persona DROP CONSTRAINT CK_TIPO_ID;
ALTER TABLE persona DROP CONSTRAINT CK_CORREO;
ALTER TABLE persona DROP CONSTRAINT CK_CORREO;
ALTER TABLE conductor DROP CONSTRAINT CK_ESTADO_COND;
ALTER TABLE conductor DROP CONSTRAINT CK_LICENCIA;
ALTER TABLE vehiculo DROP CONSTRAINT CK_ESTADO_VEHI;
ALTER TABLE solicitud DROP CONSTRAINT CK_MONEDA;
ALTER TABLE solicitud DROP CONSTRAINT CK_ESTADO_SOL;
ALTER TABLE cliente DROP CONSTRAINT CK_NUM_TARJETA;
ALTER TABLE tarjeta DROP CONSTRAINT CK_TARJETA_LEN;

--- XSECUENCIAS
DROP SEQUENCE PERSONA_ID; 
DROP SEQUENCE SOLICITUD_ID; 
DROP SEQUENCE UBICACION_ID; 

--- XDISPARADORES
DROP TRIGGER PERSON_TRIGGER; 
DROP TRIGGER DRIVER_TRIGGER ; 
DROP TRIGGER SOLICITUD_TRIGGER; 
DROP TRIGGER ADD_VEHICLE_TRIGGER; 
DROP TRIGGER ADD_MOTO_TRIGGER; 
DROP TRIGGER ADD_AUTOMOVIL_TRIGGER; 
DROP TRIGGER ADD_CAMION_TRIGGER; 
DROP TRIGGER MD_VEHICULO_TRIGGER; 
DROP TRIGGER MD_ESTADO_VEHICULO_TRIGGER; 
DROP TRIGGER UPDATE_UBICACION; 

--- XCRUD
DROP PACKAGE PKG_DRIVER;
DROP PACKAGE PKG_CLIENT;
