--- CLIENTE
CREATE OR REPLACE PACKAGE PA_CLIENTE IS
    PROCEDURE ADD_SOLICITUD(
        xClienteId IN NUMBER,
        xPosicion2 IN NUMBER,
        xPosicion1 IN NUMBER
    );

    PROCEDURE ADD_POSICION(
        xLongitud IN NUMBER,
        xLatitud IN NUMBER
    );

    PROCEDURE UPDATE_SOLICITUD(
        xClienteId IN NUMBER,
        xFechaViaje IN DATE,
        xPrecio IN NUMBER, 
        xEstado IN CHAR
    );
        
END PA_CLIENTE ;
/

--- ANALISTA CLIENTES
CREATE OR REPLACE PACKAGE PA_ANALISTA_CLIENTES IS
    FUNCTION READ_HIGHEST_MOUNTS
        RETURN SYS_REFCURSOR;

    FUNCTION READ_MOST_CANCELED_CLIENTS
        RETURN SYS_REFCURSOR;        
END PA_CLIENTE ;
/