--- CLIENTE
CREATE OR REPLACE PACKAGE PA_CLIENTE IS
    PROCEDURE ADD_CLIENT(
        xTipoId IN VARCHAR,
        xNumeroId IN VARCHAR,
        xNombre IN VARCHAR,
        xCelular IN VARCHAR,
        xEmail IN VARCHAR,
        xLicencia IN VARCHAR,
        xNacimiento IN DATE,
        xIdioma IN VARCHAR
        );
    
    PROCEDURE ADD_SOLICITUD(
        xClienteId IN NUMBER,
        xPosicion2 IN NUMBER,
        xPosicion1 IN NUMBER
    );

    PROCEDURE ADD_POSICION(
        xLongitud IN NUMBER,
        xLatitud IN NUMBER
    );

    PROCEDURE ADD_FAV_UBICACION(
        xCliente IN NUMBER,
        xNombre IN VARCHAR,
        xDireccion IN VARCHAR,
        xPosicion IN NUMBER
        );

    PROCEDURE DELETE_FAV_UBICACION(
        xCliente IN NUMBER,
        xNombre IN VARCHAR
        );

    PROCEDURE UPDATE_SOLICITUD(
        xClienteId IN NUMBER,
        xFechaViaje IN DATE,
        xPrecio IN NUMBER, 
        xEstado IN CHAR
    );

    -- READ POSICION
    FUNCTION READ_POSICION RETURN SYS_REFCURSOR;
        
    -- READ FAV LOCATION
    FUNCTION READ_FAV_LOCATION(
        xIdPersona IN NUMBER
    ) RETURN SYS_REFCURSOR;

    -- READ CLIENTES
    FUNCTION READ_CLIENT RETURN SYS_REFCURSOR;

    -- READ SOLICITUDES
    FUNCTION READ_SOLICITUD (
        xIdPersona IN NUMBER
    )RETURN SYS_REFCURSOR;

END PA_CLIENTE ;
/

--- ANALISTA CLIENTES
CREATE OR REPLACE PACKAGE PA_ANALISTA_CLIENTES IS
    FUNCTION READ_HIGHEST_MOUNTS
        RETURN SYS_REFCURSOR;

    FUNCTION READ_MOST_CANCELED_CLIENTS
        RETURN SYS_REFCURSOR;        
END PA_ANALISTA_CLIENTES ;
/